---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint
  yamllint .
  flake8
platforms:
  - name: centos7
    image: "centos:7"
    command: /sbin/init
    privileged: True
  - name: centos8
    image: "centos:8"
    command: /sbin/init
    privileged: True
  - name: amzlinux2
    image: "amazonlinux:2"
    command: /usr/lib/systemd/systemd
    privileged: True
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../shared-resources/playbooks/playbook.yml
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../shared-resources/tests

